### ISSUE TITLE
Tiff not working on devices

### ISSUE THREAD

**Issue by jeremyquinn** [behoernchen/Iconizer#2]
I believe that the TIFF images output by this application are not working on iOS devices, only on the iOS Simulator.

**Comment by behoernchen** [comment]
Thanks! I've changed the filetype to *.png. Hopefully it works now. It would be nice if someone would test this since, sadly, I don't own an iDevice.

[New Release](https://github.com/behoernchen/Iconizer/releases/tag/1.1.1)

**Comment by jeremyquinn** [comment]
That fixed the problem as far as I can see.
Many thanks.

**Comment by behoernchen** [comment]
Alright! Thanks.
