### ISSUE TITLE
won't work in Yosemite

### ISSUE THREAD

**Issue by liuyunclouder** [behoernchen/iconizer#4]
won't work in Yosemite，export
![image](https://cloud.githubusercontent.com/assets/1249065/9881038/d45ef44e-5c00-11e5-8e4c-8d00e3a1e48b.png)

**Comment by behoernchen** [comment]
Thanks!
Since El Capitan will be released this month I probably won't fix this. But (Version 2.0)[https://github.com/behoernchen/Iconizer/releases/tag/2.0] was build with Yosemite, so that version should work properly.

**Comment by behoernchen** [comment]
Thanks!
Since El Capitan will be released this month I probably won't fix this. But [Version 2.0](https://github.com/behoernchen/Iconizer/releases/tag/2.0) was build with Yosemite, so that version should work properly.

**Comment by behoernchen** [comment]
Release of El Capitan.
