### ISSUE TITLE
Build failed in AppIcon.swift

### ISSUE THREAD

**Issue by cbrands** [behoernchen/iconizer#5]
in AppIcon.swift line 94
 var jsonFile = ContentsJSON(forType: AssetType.AppIcon, andPlatforms: self.images.keys.array)

I get the following error
'array' is unavailable: please construct an Array from your lazy sequence: Array(...)

OS X: El Capitan
Xcode: 7.0.1

**Comment by behoernchen** [comment]
Oops! Forgot to push this [change](https://github.com/behoernchen/iconizer/commit/a11d8fb079961c93b23fb782f1cb523379eb83e5).

Thanks! It should work now. ;-)

**Comment by cbrands** [comment]
Yup it works. Thanks.
